services:
  db:
    image: postgres:15-alpine
    container_name: gymlog_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: ./backend
      dockerfile: ./GymLog.Api/Dockerfile
    container_name: gymlog_api
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    ports:
      - "8080:8080"

volumes:
  postgres_data:
