export * from "./Home";
export * from "./Login";
export * from "./Register";
export * from "./Workouts";
export * from "./History";
export * from "./Exercises";
export * from "./WorkoutDetails";
export * from "./ExerciseDetails";
export * from "./NotFound";